export const getStyles = (isMobile, headerVisible) => ({
  bg: {
    minHeight: '100vh',
    backgroundImage: 'url(/olympia_background.png)',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    backgroundAttachment: isMobile ? 'scroll' : 'fixed',
  },
  overlay: {
    minHeight: '100vh',
    background:
      'linear-gradient(180deg, rgba(6, 40, 25, 0.70) 0%, rgba(243, 244, 246, 0.92) 36%, rgba(243, 244, 246, 0.98) 100%)',
    paddingBottom: isMobile ? 96 : 48,
  },
  header: {
    background: 'linear-gradient(135deg, rgba(22, 101, 52, 0.95), rgba(6, 95, 70, 0.95))',
    color: '#fff',
    borderRadius: 0,
    padding: isMobile ? '22px 14px' : '32px 16px',
    position: 'sticky',
    top: 0,
    zIndex: 5,
    backdropFilter: 'blur(8px)',
    transform: headerVisible ? 'translateY(0)' : 'translateY(-100%)',
    transition: 'transform 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    willChange: 'transform',
  },
  headerTitle: {
    fontWeight: 800,
    letterSpacing: 0.2,
    fontFamily: 'serif',
    lineHeight: 1.1,
  },
  topNav: {
    marginTop: 14,
    display: isMobile ? 'none' : 'flex',
    gap: 10,
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  shell: { marginTop: isMobile ? 16 : 18 },
  card: {
    borderRadius: 18,
    background: 'rgba(255,255,255,0.94)',
    boxShadow: '0 10px 30px rgba(0,0,0,0.12)',
    border: '1px solid rgba(15, 23, 42, 0.06)',
  },
  sectionTitleWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  pillRow: { display: 'flex', gap: 10, flexWrap: 'wrap', marginTop: 12 },
  primaryBtn: {
    backgroundColor: '#f59e0b',
    color: '#111827',
    fontWeight: 800,
    borderRadius: 14,
    padding: isMobile ? '12px 14px' : '12px 16px',
    textTransform: 'none',
  },
  secondaryBtn: {
    backgroundColor: '#2563eb',
    color: '#fff',
    fontWeight: 800,
    borderRadius: 14,
    padding: isMobile ? '10px 12px' : '10px 14px',
    textTransform: 'none',
  },
  bottomNav: {
    position: 'fixed',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 10,
    padding: 10,
    display: isMobile ? 'block' : 'none',
  },
  bottomNavInner: {
    margin: '0 auto',
    maxWidth: 720,
    background: 'rgba(255,255,255,0.94)',
    border: '1px solid rgba(15, 23, 42, 0.08)',
    boxShadow: '0 14px 40px rgba(0,0,0,0.18)',
    borderRadius: 18,
    padding: '8px 8px',
    display: 'flex',
    justifyContent: 'space-between',
    gap: 8,
    overflowX: 'auto',
  },
  bottomNavBtn: {
    minWidth: 92,
    borderRadius: 14,
    textTransform: 'none',
    fontWeight: 800,
    padding: '10px 10px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    lineHeight: 1.1,
  },
});
